-- SQL script to insert all original quiz questions into the questions table
-- Make sure your table matches the required schema before running this script

INSERT INTO questions (question, option_a, option_b, option_c, option_d, answer, topic, difficulty) VALUES
('What is the capital of France?', 'Paris', 'London', 'Berlin', 'Madrid', 'a', 'general', 'easy'),
('Who wrote the Declaration of Independence?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'John Adams', 'b', 'history', 'medium'),
('Which planet is known as the Red Planet?', 'Earth', 'Mars', 'Jupiter', 'Venus', 'b', 'science', 'easy'),
('Who is known as the God of Cricket?', 'Virat Kohli', 'Ricky Ponting', 'Sachin Tendulkar', 'Brian Lara', 'c', 'sports', 'medium'),
('Which religion is the Bhagavad Gita associated with?', 'Christianity', 'Islam', 'Hinduism', 'Buddhism', 'c', 'religion', 'easy'),
('Who is the current President of the United States (2023)?', 'Donald Trump', 'Joe Biden', 'Barack Obama', 'George Bush', 'b', 'politics', 'easy'),
('Which is the largest ocean in the world?', 'Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'c', 'general', 'easy'),
('Which country has the most population in the world?', 'India', 'USA', 'China', 'Indonesia', 'a', 'general', 'medium'),
('What is the currency of Japan?', 'Yen', 'Won', 'Rupee', 'Dollar', 'a', 'general', 'easy'),
('Which planet is closest to the Sun?', 'Venus', 'Mars', 'Mercury', 'Earth', 'c', 'general', 'easy'),
('How many continents are there?', '5', '6', '7', '8', 'c', 'general', 'easy'),
('Which country is called the Land of the Rising Sun?', 'Japan', 'Thailand', 'China', 'India', 'a', 'general', 'easy'),
('What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 'c', 'general', 'medium'),
('Which is the longest river in the world?', 'Nile', 'Amazon', 'Yangtze', 'Mississippi', 'a', 'general', 'medium'),
('Which country hosted the 2020 Summer Olympics?', 'China', 'Japan', 'Brazil', 'USA', 'b', 'general', 'medium'),
('Which language has the most native speakers?', 'Hindi', 'English', 'Mandarin Chinese', 'Spanish', 'c', 'general', 'medium'),
('Who was the first President of the United States?', 'Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams', 'b', 'history', 'easy'),
('In which year did World War II end?', '1945', '1942', '1939', '1950', 'a', 'history', 'easy'),
('Who discovered America in 1492?', 'Marco Polo', 'Christopher Columbus', 'Ferdinand Magellan', 'Amerigo Vespucci', 'b', 'history', 'easy'),
('Which empire was ruled by Julius Caesar?', 'Roman Empire', 'Ottoman Empire', 'Mongol Empire', 'British Empire', 'a', 'history', 'medium'),
('Who was the Prime Minister of the UK during World War II?', 'Winston Churchill', 'Tony Blair', 'Margaret Thatcher', 'Neville Chamberlain', 'a', 'history', 'medium'),
('Which Indian leader is known for the Salt March?', 'Subhas Chandra Bose', 'Bhagat Singh', 'Mahatma Gandhi', 'Jawaharlal Nehru', 'c', 'history', 'easy'),
('What wall was torn down in 1989 symbolizing the end of Cold War?', 'Berlin Wall', 'Great Wall of China', 'Iron Curtain', 'Wall of Europe', 'a', 'history', 'medium'),
('Who was the Mughal emperor during the Battle of Panipat (1526)?', 'Babur', 'Akbar', 'Aurangzeb', 'Shah Jahan', 'a', 'history', 'medium'),
('Who was known as the "Iron Lady" of British politics?', 'Queen Elizabeth II', 'Margaret Thatcher', 'Theresa May', 'Angela Merkel', 'b', 'history', 'medium'),
('Which war was fought between the North and South regions of the United States?', 'Revolutionary War', 'World War I', 'American Civil War', 'Vietnam War', 'c', 'history', 'medium'),
('How many players are there in a football (soccer) team on the field?', '9', '10', '11', '12', 'c', 'sports', 'easy'),
('Who has won the most Grand Slam titles in men''s tennis?', 'Roger Federer', 'Novak Djokovic', 'Rafael Nadal', 'Pete Sampras', 'b', 'sports', 'medium'),
('Which country won the FIFA World Cup in 2018?', 'Germany', 'Brazil', 'France', 'Argentina', 'c', 'sports', 'easy'),
('How many rings are there in the Olympic symbol?', '4', '5', '6', '7', 'b', 'sports', 'easy'),
('Which country has won the most Cricket World Cups?', 'India', 'Australia', 'England', 'West Indies', 'b', 'sports', 'medium'),
('Who is known as "The Lightning Bolt" in athletics?', 'Usain Bolt', 'Tyson Gay', 'Justin Gatlin', 'Carl Lewis', 'a', 'sports', 'easy'),
('Which Indian cricketer is also known as "Captain Cool"?', 'Virat Kohli', 'Sachin Tendulkar', 'MS Dhoni', 'Rohit Sharma', 'c', 'sports', 'easy'),
('Which sport uses a pommel horse?', 'Gymnastics', 'Equestrian', 'Wrestling', 'Judo', 'a', 'sports', 'medium'),
('What is the national sport of Canada?', 'Ice Hockey', 'Lacrosse', 'Baseball', 'Basketball', 'b', 'sports', 'medium'),
('Which city hosted the Olympic Games in 2016?', 'Tokyo', 'Beijing', 'London', 'Rio de Janeiro', 'd', 'sports', 'medium'),
('Who is the Prime Minister of India as of 2024?', 'Rahul Gandhi', 'Narendra Modi', 'Amit Shah', 'Manmohan Singh', 'b', 'politics', 'easy'),
('Which political system has a king or queen as head of state?', 'Democracy', 'Monarchy', 'Communism', 'Republic', 'b', 'politics', 'easy'),
('Which U.S. president resigned after the Watergate scandal?', 'Bill Clinton', 'Richard Nixon', 'Ronald Reagan', 'George Bush', 'b', 'politics', 'medium'),
('The United Nations headquarters is located in which city?', 'Geneva', 'Paris', 'New York City', 'London', 'c', 'politics', 'easy'),
('Who is the current Chancellor of Germany (2024)?', 'Angela Merkel', 'Olaf Scholz', 'Frank-Walter Steinmeier', 'Heiko Maas', 'b', 'politics', 'medium'),
('Which document begins with "We the People"?', 'Bill of Rights', 'Constitution of India', 'US Constitution', 'Declaration of Independence', 'c', 'politics', 'medium'),
('Which Indian article provides Right to Equality?', 'Article 21', 'Article 14', 'Article 19', 'Article 370', 'b', 'politics', 'medium'),
('What is the minimum age to become the President of India?', '25', '30', '35', '40', 'c', 'politics', 'easy'),
('Which body is known as the "Upper House" in the Indian Parliament?', 'Lok Sabha', 'Vidhan Sabha', 'Rajya Sabha', 'Panchayat', 'c', 'politics', 'easy'),
('Who appoints the Chief Election Commissioner in India?', 'Prime Minister', 'President', 'Supreme Court', 'Lok Sabha Speaker', 'b', 'politics', 'medium'),
('What is the chemical symbol for water?', 'O2', 'CO2', 'H2O', 'HO', 'c', 'science', 'easy'),
('How many bones are there in the adult human body?', '198', '206', '201', '210', 'b', 'science', 'medium'),
('What gas do plants absorb from the atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'c', 'science', 'easy'),
('What planet is known as the "Gas Giant"?', 'Mars', 'Jupiter', 'Venus', 'Saturn', 'b', 'science', 'medium'),
('Which part of the cell contains the genetic material?', 'Nucleus', 'Ribosome', 'Mitochondria', 'Cytoplasm', 'a', 'science', 'medium'),
('Which vitamin is produced by the body when exposed to sunlight?', 'Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin E', 'c', 'science', 'easy'),
('What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Granite', 'c', 'science', 'easy'),
('What is the speed of light?', '300,000 km/s', '150,000 km/s', '100,000 km/s', '500,000 km/s', 'a', 'science', 'medium'),
('Which scientist proposed the theory of relativity?', 'Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Stephen Hawking', 'c', 'science', 'medium'),
('What is the boiling point of water at sea level?', '90°C', '100°C', '80°C', '110°C', 'b', 'science', 'easy'),
('Which religion considers the Quran as its holy book?', 'Christianity', 'Islam', 'Hinduism', 'Buddhism', 'b', 'religion', 'easy'),
('Who is the founder of Buddhism?', 'Lord Krishna', 'Jesus Christ', 'Gautama Buddha', 'Prophet Muhammad', 'c', 'religion', 'easy'),
('Which religion worships in a synagogue?', 'Islam', 'Christianity', 'Judaism', 'Hinduism', 'c', 'religion', 'medium'),
('In Christianity, who is considered the Son of God?', 'Moses', 'Jesus Christ', 'David', 'Noah', 'b', 'religion', 'easy'),
('Which festival is known as the "Festival of Lights" in Hinduism?', 'Holi', 'Navratri', 'Diwali', 'Janmashtami', 'c', 'religion', 'easy'),
('Which religion follows the Eightfold Path?', 'Hinduism', 'Buddhism', 'Islam', 'Christianity', 'b', 'religion', 'medium'),
('What is the holy book of Sikhism?', 'Vedas', 'Quran', 'Bible', 'Guru Granth Sahib', 'd', 'religion', 'medium'),
('Ramadan is a holy month in which religion?', 'Islam', 'Christianity', 'Judaism', 'Hinduism', 'a', 'religion', 'easy'),
('Which religion believes in reincarnation as a key concept?', 'Islam', 'Hinduism', 'Christianity', 'Judaism', 'b', 'religion', 'medium'),
('Who is regarded as the last prophet in Islam?', 'Isa (Jesus)', 'Moses', 'Abraham', 'Muhammad', 'd', 'religion', 'easy');
-- (continue for all questions in your array) 